import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const promptSources = {
  'knowledge-analyzer': 'prompts/knowledge-analyzer/prompt.md',
  'question-generator': 'prompts/question-generator/prompt.md',
  'question-reviewer': 'prompts/question-reviewer/prompt.md',
  'answer-evaluator': 'prompts/answer-evaluator/prompt.md',
  'learning-recommendation': 'prompts/learning-recommendation/prompt.md',
  'skill-router': 'prompts/skill-router/prompt.md',
};

const prompts = {};

for (const [skill, relativePath] of Object.entries(promptSources)) {
  const prompt = await readFile(resolve(root, relativePath), 'utf8');
  prompts[skill] = prompt.trim();
}

const outputPath = resolve(root, 'cloud-functions/api/generated-prompts.js');
const output = `// This file is generated by scripts/sync-prompts.mjs.
// Edit prompts/*/prompt.md, then run npm run sync:prompts.

export const PROMPTS = ${JSON.stringify(prompts, null, 2)};
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, output, 'utf8');

console.log(`Synced ${Object.keys(prompts).length} prompts to ${outputPath}`);
